### PR TITLE
 2FOC Firmware -  fix compilation error

### LINKED ISSUE #152: Fix building problem - MPLAB
When building the 2FOC.V3 project, the following error appears:

```../src/ecan.c:827:37: error: conflicting types for 'int8_t'```

 It is a problem related to the new compiler version. The old version contains this line:

https://github.com/robotology/icub-firmware/blob/b6c0a716bb75105fd1d62cfce6ae05c7d649df9b/emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/src/ecan.c#L827

that causes that error.

The fix is:

https://github.com/isorrentino/icub-firmware/blob/afd340abb343c5d5502970961266feaac327dd8a/emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/src/ecan.c#L1135

### PR DESCRIPTION
**Pull request by giovannipizzolante**
This fix #152 . As suggested by @marcoaccame the compilation error has been fixed by removing ```typedef``` lines and putting an ```#include "stdint.h"``` .

### CODE REVIEW

File: emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/src/ecan.c [hunk 1]
```diff
@@ -6,7 +6,7 @@
 
 #include <p33FJ128MC802.h>
 #include <string.h>
-
+#include "stdint.h"
```
Comment (traversaro) [inline emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/src/ecan.c:9]: Thanks @giovannipizzolante , I have a nitpick (i.e. a comment that you can safely ignore, see https://google.github.io/eng-practices/review/reviewer/looking-for.html#style). 

In C/C++, the main difference between includes that are added with `<include-name.h>` vs the one that are included with  `"include-name.h"` is that the latter one, i.e. the one with the quote, also looks in the same directory of this file to search for the included .h file (see https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename). For this reason, the style with which normally system includes are added is the one with the `<` , `>`. 
```suggestion
#include <stdint.h>
```

**Review by traversaro — APPROVED** [review]

File: emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/src/ecan.c (hunk 1 above)
Comment (giovannipizzolante) [reply emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/src/ecan.c:9]: thanks @traversaro !

**Comment by traversaro** [comment]
@marcoaccame Feel free to let @giovannipizzolante if you prefer brackets or commas for the include (see https://github.com/robotology/icub-firmware/pull/158#discussion_r558293317), thanks!

**Comment by marcoaccame** [comment]
Hi @traversaro: thanks for the suggestion. i have committed it. an thanks @giovannipizzolante for the test.
